---
# These tasks install php 7.4

- name: epel-release
  yum: name=epel-release state=installed

- name: Install remi repo.
  yum:
    name: "{{ remi_repo_url }}"
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present

- name: install php74
  yum: name={{ packages }} enablerepo=epel,remi,remi-php74 state=installed
  vars:
    packages:
    - php
    - php-mcrypt
    - php-mbstring
    - php-fpm
    - php-gd
    - php-xml
    - php-pdo
    - php-zip
    - php-cli
    - php-mysqlnd
    - php-devel
    - php-curl
    - php-pear
    - php-bcmath
    - php-json
    - php-mysql
    - php-pecl-xdebug.x86_64

- name: Create xdebug.ini
  template: src=15-xdebug.ini.j2 dest=/etc/php.d/15-xdebug.ini